package com.shreespark.pos_api.common.enums;

public enum Permission {
    BILLING_CREATE,
    BILLING_VIEW_ALL,
    BILLING_APPLY_DISCOUNT,
    PRODUCTS_CREATE,
    PRODUCTS_EDIT,
    PRODUCTS_DELETE,
    BARCODE_GENERATE,
    CUSTOMERS_VIEW,
    CUSTOMERS_EDIT,
    KHATA_VIEW,
    KHATA_RECORD_PAYMENT,
    KHATA_MANUAL_ENTRY,
    REPORTS_VIEW,
    REMINDERS_SEND,
    STAFF_MANAGE,
    DEVICE_MANAGE,
    SETTINGS_MANAGE
}
